### ISSUE TITLE
add compid to task results file

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#101]
add compid to task results file, then add link back to comp results into the task result template and remove compid from public pages session. this will enable the "back to comp results" link to work even if a user navigates direct to task result without passing through home page/comp page.

**Comment by biuti** [comment]
Added in template_refactor branch (https://github.com/FAI-CIVL/FAI-Airscore/commit/3611829386379b8e4624a2d1d4728e24aaa4aff9)
