### ISSUE TITLE
On mac, flask-mail not there.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#104]
When I follow the readme, the docker quickstart, development version, I get a runtime error:

```
> git clone https://github.com/FAI-CIVL/FAI-Airscore.git
> cd FAI-Airscore
> docker compose -f docker-compose-dev.yml up
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1215ee6]

goroutine 1 [running]:
github.com/spf13/cobra.(*Command).Name(0x0, 0xc000114060, 0x4)
	github.com/spf13/cobra@v1.0.0/command.go:1258 +0x26
main.exit(0xc0002d6000, 0x29762e5, 0x7, 0x2c22360, 0xc000136340, 0x2972e45, 0x4)
	github.com/docker/compose-cli/cli/main.go:228 +0x25e
main.main()
	github.com/docker/compose-cli/cli/main.go:208 +0xe58
```

```
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G14033
```

**Comment by philderbeast** [comment]
I'm using the docker desktop (community editon) for mac.

![Screen Shot 2020-10-17 at 3 27 06 PM](https://user-images.githubusercontent.com/633283/96351952-5b1d1d80-108d-11eb-859c-5a85f4773da4.png)

**Comment by kuaka** [comment]
I have not used docker desktop, however the command should be docker-compose, not docker.
sudo docker-compose -f docker-compose-dev.yml up
or 
docker-compose -f docker-compose-dev.yml up

you may need to install docker compose. We should add this to the readme

**Comment by philderbeast** [comment]
Odd, I thought I'd done a copy and paste from the readme to the command line. Should have double checked.

```
> docker-compose -f docker-compose-dev.yml up
WARNING: The FLASK_PORT variable is not set. Defaulting to a blank string.
WARNING: The REDIS_CONTAINER variable is not set. Defaulting to a blank string.
WARNING: The WEB_SERVER_CONTAINER variable is not set. Defaulting to a blank string.
WARNING: The MAIL_SERVER variable is not set. Defaulting to a blank string.
WARNING: The MAIL_PORT variable is not set. Defaulting to a blank string.
WARNING: The MAIL_USE_TLS variable is not set. Defaulting to a blank string.
WARNING: The MAIL_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The MAIL_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ADMINS variable is not set. Defaulting to a blank string.
WARNING: The MYSQLHOST variable is not set. Defaulting to a blank string.
WARNING: The DATABASE variable is not set. Defaulting to a blank string.
WARNING: The MYSQLUSER variable is not set. Defaulting to a blank string.
WARNING: The MYSQLPASSWORD variable is not set. Defaulting to a blank string.
WARNING: The XCONTEST_USER variable is not set. Defaulting to a blank string.
WARNING: The XCONTEST_PASS variable is not set. Defaulting to a blank string.
WARNING: The TELEGRAM_API variable is not set. Defaulting to a blank string.
WARNING: The TELEGRAM_CHANNEL variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose-dev.yml' is invalid because:
services.flask-dev.ports contains an invalid type, it should be a number, or an object
```

**Comment by philderbeast** [comment]
So `docker-compose` runs now but with errors reported in the compose file.

**Comment by kuaka** [comment]
looks like you are missing the .env file. you can use the .env.example as a starting point. Take a copy and rename to .env
the same applies to defines.yaml.example  - > defines.yaml

**Comment by philderbeast** [comment]
> looks like you are missing the .env file. you can use the .env.example as a starting point. Take a copy and rename to .env
> the same applies to defines.yaml.example - > defines.yaml

OK if I add those instructions to the readme?

**Comment by kuaka** [comment]
It should be there, just above docker quickstart. However the readme is obviously not clear and needs work. Would be great to have your input as you are coming from the new user perspective. please by all means change and PR

**Comment by philderbeast** [comment]
It says in the `.env.example` that these are overrides but then I'd assume that if I didn't want any
overrides I could get going without an `.env` file.

https://github.com/FAI-CIVL/FAI-Airscore/blob/0c548ec32ed149eb63ffbfb0c9bc97d95eb1cefe/.env.example#L1

**Comment by philderbeast** [comment]
I installed mysql, created a schema, ran the provided `airscore.sql` script, added a user for this database, added entries in `.env` for the user and database.

```
> docker-compose -f docker-compose-dev.yml up
...
flask_dev    | [FLASK]
manage       | Traceback (most recent call last):
manage       |   File "/home/sid/.local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
manage       |     __import__(module_name)
manage       |   File "/app/autoapp.py", line 3, in <module>
manage       |     from airscore.app import create_app
manage       |   File "/app/airscore/app.py", line 7, in <module>
manage       |     from airscore import commands, public, user, internal
manage       |   File "/app/airscore/public/__init__.py", line 3, in <module>
manage       |     from . import views  # noqa
manage       |   File "/app/airscore/public/views.py", line 15, in <module>
manage       |     from airscore.extensions import login_manager
manage       |   File "/app/airscore/extensions.py", line 11, in <module>
manage       |     from flask_mail import Mail
manage       | ModuleNotFoundError: No module named 'flask_mail'
```

**Comment by kuaka** [comment]
looks like flask-mail did not install even though it is in the requirements file. @biuti have you had any issues with this?

You can try running:
sudo docker exec -it --user 1000 flask_dev /bin/bash
this will get you into the dev containter with a bash prompt.
then you can try:
Pip install Flask-Mail 
this should install it or tell you that it is already installed

**Comment by kuaka** [comment]
> It says in the `.env.example` that these are overrides but then I'd assume that if I didn't want any overrides I could get going without an `.env` file.
> 
> https://github.com/FAI-CIVL/FAI-Airscore/blob/0c548ec32ed149eb63ffbfb0c9bc97d95eb1cefe/.env.example#L1

good catch, this needs updating as they are no longer overides for dev but necessary settings for prod and dev

**Comment by kuaka** [comment]
> > It says in the `.env.example` that these are overrides but then I'd assume that if I didn't want any overrides I could get going without an `.env` file.
> > https://github.com/FAI-CIVL/FAI-Airscore/blob/0c548ec32ed149eb63ffbfb0c9bc97d95eb1cefe/.env.example#L1
> 
> good catch, this needs updating as they are no longer overides for dev but necessary settings for prod and dev

Dev has been updated with https://github.com/FAI-CIVL/FAI-Airscore/commit/030da97ba06d419644bf3c1dab667173fb10a4d7 to address this.

**Comment by philderbeast** [comment]
Should I be setting `dev` as the branch to merge to with pull requests?

**Comment by philderbeast** [comment]
> looks like flask-mail did not install even though it is in the requirements file. @biuti have you had any issues with this?
> 
> You can try running:
> sudo docker exec -it --user 1000 flask_dev /bin/bash
> this will get you into the dev containter with a bash prompt.
> then you can try:
> Pip install Flask-Mail
> this should install it or tell you that it is already installed

I followed these instructions but got the same error.

```
sid@9e03bb78dae5:/app$ pip install Flask-Mail
Defaulting to user installation because normal site-packages is not writeable
Collecting Flask-Mail
  Downloading Flask-Mail-0.9.1.tar.gz (45 kB)
     |████████████████████████████████| 45 kB 948 kB/s
Requirement already satisfied: Flask in /home/sid/.local/lib/python3.8/site-packages (from Flask-Mail) (1.1.1)
Requirement already satisfied: blinker in /home/sid/.local/lib/python3.8/site-packages (from Flask-Mail) (1.4)
Requirement already satisfied: click>=5.1 in /home/sid/.local/lib/python3.8/site-packages (from Flask->Flask-Mail) (7.0)
Requirement already satisfied: Jinja2>=2.10.1 in /home/sid/.local/lib/python3.8/site-packages (from Flask->Flask-Mail) (2.11.1)
Requirement already satisfied: itsdangerous>=0.24 in /home/sid/.local/lib/python3.8/site-packages (from Flask->Flask-Mail) (1.1.0)
Requirement already satisfied: Werkzeug>=0.15 in /home/sid/.local/lib/python3.8/site-packages (from Flask->Flask-Mail) (1.0.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/sid/.local/lib/python3.8/site-packages (from Jinja2>=2.10.1->Flask->Flask-Mail) (1.1.1)
Building wheels for collected packages: Flask-Mail
  Building wheel for Flask-Mail (setup.py) ... done
  Created wheel for Flask-Mail: filename=Flask_Mail-0.9.1-py3-none-any.whl size=7568 sha256=88c2f870a4800d6e616dd86acb37b11ebebff752b85e084fa7a27cf4b306de7d
  Stored in directory: /home/sid/.cache/pip/wheels/98/bc/8c/34c329e4d7efeaf7b9886db0c76d0b23170e54de443f688e3c
Successfully built Flask-Mail
Installing collected packages: Flask-Mail
Successfully installed Flask-Mail-0.9.1
WARNING: You are using pip version 20.0.2; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
sid@9e03bb78dae5:/app$ exit
```

**Comment by kuaka** [comment]
yes you can use dev branch.
I have just done a fresh setup of airscore & build with docker (using master branch, but dev should work the same) and had no issues with flask-mail. this is a real puzzle to me as this is exactly the thing that docker was designed to avoid (works on mine but not yours). @biuti any ideas?

**Comment by philderbeast** [comment]
I'm only seeing this problem on mac. I wasn't able to reproduce it on ubuntu, although there I did have to supplement the command to bring it up and run as sudo:

```diff
-- > docker-compose -f docker-compose-dev.yml up
++ > sudo docker-compose -f docker-compose-dev.yml up --build
```

I'll narrow this issue down to the flask-mail issue on mac and create pull requests for instructions in the readme that might help new contributing devs or testers.

**Comment by philderbeast** [comment]
@kuaka I'm not encountering this issue with the [local db dev](https://github.com/FAI-CIVL/FAI-Airscore/tree/local_db_dev) branch.

**Comment by kuaka** [comment]
that's great. It is a really strange one. Something that docker is supposed to solve.. and something that I cannot test as I don't have a mac. I can't think of anything that would create a difference with the two branches either. Perhaps it will go away when we merge into development (or perhaps it has gone if you rebuild in development, i.e. the 'fix' is already in development)

**Comment by kuaka** [comment]
@philderbeast  can this be closed?
