### ISSUE TITLE
There are three main services?

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#108]
The readme has a leader for introducing three main services but doesn't say what these are.

> There are three main services:

https://github.com/FAI-CIVL/FAI-Airscore/blame/master/README.md#L34

**Comment by kuaka** [comment]
There is a production docker, dev docker and in dev there is dev server and manage that runs the unit tests automatically. Readme needs to explain this better

**Comment by kuaka** [comment]
I believe this can be closed with the latest readme in development branch
