### ISSUE TITLE
Test setup that includes a database ready to go.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#109]
For those that want to test airscore locally rather than develop it locally, could we please add a minimal setup that doesn't require a manual setup of a database?

> Airscore uses a Mysql database. The database is not included in the docker containers.

**Comment by philderbeast** [comment]
We have `docker-compose-dev.yml` for which the database to use is configured by reading from `.env`. Could we have another `docker-compose-dev-db.yml` for which mysql is installed, an `airscore` database has been created, the `airscore.sql` script already run and where there's a user already setup and used by the other parts of airscore in this setting so that no configuration is necessary?

**Comment by kuaka** [comment]
This is a great idea. In theory if there are no users in the user table the application will start up with the homepage allowing a user to be set up, so the user could be done that way or as you say setup directly with the database before beginning. I will look into it.

**Comment by kuaka** [comment]
I have created a branch local_db_dev. See the updated readme here but it gives you the option to run a docker-compose file that includes a MySQL DB (automatically created and populated with the airscore schema).
I have tested and squashed some bugs. I have setup a comp, imported waypoints, manually added pilots, set a task, processed 2 igc files and created a task score. Beyond that I haven't tested.
Before merging to development it would be great to have someone else run through the install.

**Comment by philderbeast** [comment]
Trying a naive setup without touching `.env` or `defines.yaml` on the mac after a fresh clone:

```
> git clone https://github.com/FAI-CIVL/FAI-Airscore.git
> cd FAI-Airscore
> git checkout local_db_dev
> docker-compose -f docker-compose-dev.yml up
WARNING: The FLASK_PORT variable is not set. Defaulting to a blank string.
WARNING: The REDIS_CONTAINER variable is not set. Defaulting to a blank string.
WARNING: The WEB_SERVER_CONTAINER variable is not set. Defaulting to a blank string.
WARNING: The MAIL_SERVER variable is not set. Defaulting to a blank string.
WARNING: The MAIL_PORT variable is not set. Defaulting to a blank string.
WARNING: The MAIL_USE_TLS variable is not set. Defaulting to a blank string.
WARNING: The MAIL_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The MAIL_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The ADMINS variable is not set. Defaulting to a blank string.
WARNING: The MYSQLHOST variable is not set. Defaulting to a blank string.
WARNING: The DATABASE variable is not set. Defaulting to a blank string.
WARNING: The MYSQLUSER variable is not set. Defaulting to a blank string.
WARNING: The MYSQLPASSWORD variable is not set. Defaulting to a blank string.
WARNING: The XCONTEST_USER variable is not set. Defaulting to a blank string.
WARNING: The XCONTEST_PASS variable is not set. Defaulting to a blank string.
WARNING: The TELEGRAM_API variable is not set. Defaulting to a blank string.
WARNING: The TELEGRAM_CHANNEL variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose-dev.yml' is invalid because:
services.flask-dev.ports contains an invalid type, it should be a number, or an object
```

**Comment by kuaka** [comment]
you need to run the docker-compose-dev-local.yml (details are in the readme)

**Comment by philderbeast** [comment]
I should have looked at the commits first, my apologies for the bother.

**Comment by philderbeast** [comment]
I reviewed the readme and it looks like startup for the database included option is no touch save for deleting the database if need be. I get the same error:

```
> docker-compose -f docker-compose-dev-local.yml up
...
ERROR: The Compose file './docker-compose-dev-local.yml' is invalid because:
services.flask-dev-local.ports contains an invalid type, it should be a number, or an object
```

**Comment by kuaka** [comment]
You will still need to rename the env and defines files. I only set the DB vars in the compose file. I did not think to force the others from .env. I can do that tomorrow and commit. However defines will always need to be renamed although now that it doesn't contain sensitive information we can put it into git with the right name to start with.

In the meantime however please rename the two files

**Comment by philderbeast** [comment]
Fantastic work @kuaka. Thanks for prioritising it. Someone who's spinning up a test environment this way might not know or be interested in docker. I'm a docker novice. I got this error on both mac and ubuntu. Could we add an explanation about it and workaround to the readme please?

```
> cp .env.example .env
> cp defines.yaml.examples defines.yaml
> docker-compose -f docker-compose-dev-local.yml up
...
Creating redis           ... error
Creating adminer ...
Creating mysql_db_local ...
Creating flask_dev_local ...

Creating mysql_db_local  ... error
Creating adminer         ... done

Creating flask_dev_local ... done

ERROR: for redis  Cannot create container for service redis: Conflict. The container name "/redis" is already in use
by container "7e82016a681bff54a411d2d238364892f43bb1cb97fe78f0b13f4d47d26c0489".
You have to remove (or rename) that container to be able to reuse that name.

ERROR: for db  Cannot start service db: Ports are not available: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by kuaka** [comment]
As you have run docker before on airscore you will have to delete the old containers on your system. Google is your friend as I can't be sure off the top of my head (probably docker rm container_name).
I can add something to readme for sure however we're getting close to the border line of outside the scope of airscore and into docker of which there is plenty of help online. Probably not unreasonable to put something in readme though.

**Comment by philderbeast** [comment]
I made this change to `.env` to clear the redis error:

```diff
-- REDIS_CONTAINER = redis
++ REDIS_CONTAINER = redis-local-db
```

I stopped the mysql daemon installed and running as a service on the host to clear the port `3306` error.

Startup with `docker-compose` looks good but I get the following:

```
# http://localhost:5000/
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError)
(2003, "Can't connect to MySQL server on 'db' ([Errno -2] Name or service not known)")
```

**Comment by kuaka** [comment]
I have seen that before. Maybe just restart. From the readme:
Note that the first time you run the docker-compose the database setup may take longer than the application start up. In that case there will be an error. Simply wait untill the database is finished (evident in the shell) and stop and restart (ctl-c to stop)

**Comment by philderbeast** [comment]
That's it alright, a gotcha for a newcomer.

**Comment by kuaka** [comment]
yes, I am sure there will be a way to make one service wait for another on startup but I thought that it could be something that takes quite a bit of googling and experimenting. Was keen to get this up as quick as possible in the first instance.

**Comment by kuaka** [comment]
I'm optimistically hoping that no news is good news here. If it is running ok I can merge it into development.
