### ISSUE TITLE
Three flavours of getting started.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#112]
Could we split the getting started instructions 3 ways for?

1. Developers using a hosted database.
2. Developers setting up mysql on their host machine.
3. Developers and testers using a no-worries setup that works with minimal or no configuration, #109 

I tried 2 and have come tantalisingly close to getting this working.

Is there a hosted database that can be made available for devs in this project, one that is periodically blown away every so often.

**Comment by kuaka** [comment]
I think this can be closed now.
Or is there something missing?
