### ISSUE TITLE
DB setup missing table data

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#115]
The sql file to setup the database is without table data. It is just setting up the tables, views etc. 
However at least in the case of TblCountryCode, which contains country names and ISO codes, this should be populated when the DB is created. There may be other tables that also need data at creation but probably not.

**Comment by biuti** [comment]
Yes, true.
We are thinking to use a py function that creates tables and rows where needed, thought SQLAlchemy. This way we could create db independently from type, MySQL or SQLite or any other in the future.
What's your opinion?

**Comment by kuaka** [comment]
your reply would be suited to @philderbeast's question around migrations (email but related to #111). 
Yes having migrations set up this way would be great but last time I looked our DB models were not set up in the right way to do this.
In the immediate future we need to have a .sql file that people can use to setup airscore. The sql file needs to have this 1 table with data and not just structure. (simple export the table in phpmyadmin with data (in sql) and paste into the file substituting the existing setup of that table. 
However, the whole sql file needs to be generated again after addressing issue #111. i.e. after removing the int(x) and float(x) from the DB and corresponding table.py file.

**Comment by kuaka** [comment]
fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/14fa1317334def290e0bd7eb8ffc0788505cc123
