### ISSUE TITLE
Italian open URL is mashed.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#116]
Url is mashed.

![Screen Shot 2020-10-23 at 2 30 42 PM](https://user-images.githubusercontent.com/633283/97040945-bdb66380-153c-11eb-853f-906294e40787.png)

**Comment by kuaka** [comment]
This has been fixed with caef10fc035ec913a88a75a18b7fa00586d9ed63 however this commit is not in the version on server (it is in master & development however) and it only works when saving the url (so not retrospective to comps saved before commit). I will update this specific url on the server.
