### ISSUE TITLE
Don't write finished_ss="" in FsResult

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#118]
Please don't write `FsParticipant/FsResult@finished_ss=""` when `FsParticipant/FsResult[@arrival_points == '0']`. FS doesn't do this. I guard against parsing this as a time in `flare-timing` now but it adds noise when inspecting the `*.fsdb` file by eye and I would prefer if it wasn't written.

```diff
          </FsParticipant>
          <FsParticipant id="158">
            <FsFlightData finished_ss="" />
--          <FsResult arrival_points="0" finished_ss=""/>
          </FsParticipant>
          </FsParticipant>
          <FsParticipant id="158">
            <FsFlightData finished_ss="" />
++          <FsResult arrival_points="0"/>
          </FsParticipant>
```

**Comment by biuti** [comment]
So, if I understand correctly, pilots landed out before ESS have `finished_ss=""` in FsFlightData but not in FsResult.
Correct?

**Comment by philderbeast** [comment]
Yes that's right except the condition should be when `FsParticipant/FsFlightData/@finished_ss=""` don't write the same attribute to `FsParticipant/FsResult`, not the condition I mentioned in the first comment in this issue.

**Comment by biuti** [comment]
Should be fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/456cd1ee67bcfcb19a9bf888cf863874cb07e727
