### ISSUE TITLE
Attribute goal_ratio but FS uses goalratio.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#119]
Most attributes of FS are snake cased. I've noticed that airscore is exporting to `*.fsdb` a `goal_ratio` attribute but FS uses `goalratio`.

**Comment by biuti** [comment]
Fixed (development branch, commit https://github.com/FAI-CIVL/FAI-Airscore/commit/41e3d85e62ba5ddccb6674d580481f6febf3da82)
