### ISSUE TITLE
Import comp with Fs element from file with extension .fsdb or .xml

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#124]
The comp import is expecting an `*.fsdb`. This is an XML file with root element `<Fs>`. Please also allow import of `*.xml` with an `<Fs>` root element.

The current response is:

```
"POST /users/_import_comp_fsdb/ HTTP/1.1" 302 -
"GET /users/_import_comp_fsdb/ HTTP/1.1" 405 -
```

**Comment by kuaka** [comment]
I believe that this issue has been duplicated with #156  and #154

**Comment by philderbeast** [comment]
Thanks for spotting the duplication @kuaka. I'm closing this in favour of #156.
