### ISSUE TITLE
Document two sets of credentials in .env.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#129]
Please document what each set of credentials are used for and whether they should or shouldn't be the same, the field-by-field creds and those embedded in the connection string.

https://github.com/FAI-CIVL/FAI-Airscore/blob/41e3d85e62ba5ddccb6674d580481f6febf3da82/.env.example#L12-L16

**Comment by kuaka** [comment]
Documentation needed I agree (although quite self explanatory in most cases). removing the last var has been on an undocumented todo list for a while. now documented in issue #130

**Comment by kuaka** [comment]
no longer relevant as 2nd set of credentials removed (https://github.com/FAI-CIVL/FAI-Airscore/commit/826b82519bd9f7cc0032092f6ea857aa8a65b10f)
