### ISSUE TITLE
inconsistent field length in DB

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#132]
tblRegionWaypoint & tblTaskWaypoint have inconsistent field lengths for name and description. Since the data for the task waypoints comes from the region table this can lead to an error (when the data is too long). This has been fixed in the development fai db and in the sql file (see https://github.com/FAI-CIVL/FAI-Airscore/commit/b86bc9117cefb78645d97adad3585701e0875fe1 ) but will need to be fixed manually in any other DBs.

**Comment by biuti** [comment]
Changed in LP and Test.
