### ISSUE TITLE
unable to download waypoints

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#133]
There is no link/ability to download waypoints (admin or public)

**Comment by biuti** [comment]
I'll add link in region_admin.
I was thinking about a map page linked to competition page with waypoints / airspace and download links to file.
It wasn't meant to be a Airtribune like website but very few effort would be necessary. Thoughts?

**Comment by biuti** [comment]
added link to region_admin https://github.com/FAI-CIVL/FAI-Airscore/commit/19665528c7e4ac41b7750bc4b8b1cdffd603aae7

**Comment by biuti** [comment]
To add it in competition page, we need to add a reg_id column in comp table. Probably makes sense anyway, so to have a default reg_id for tasks.

**Comment by kuaka** [comment]
We have all the information in the DB already. We have the link between region and task and between task and comp.
So we can just query (with a join) and get a list of regions.

**Comment by biuti** [comment]
Yes, but you won't be able to download file untile first task is set. Is it acceptable?

**Comment by kuaka** [comment]
The most important thing is a link for admins (region admin) I wanted to test airscore local and could not download the waypoints from legapiloti.
For pilots it would be useful but not a priority. The other way of doing it is just a download waypoints page with them all available (and perhaps stating what conps they're used in.

But this should be post v1

**Comment by kuaka** [comment]
> Yes, but you won't be able to download files until first task is set. Is it acceptable?

Yes that's a good point. It's not ideal.

**Comment by kuaka** [comment]
In the case that we are not using 'waypoint library' then the regions for a comp are available before task creation.
https://github.com/FAI-CIVL/FAI-Airscore/blob/41e3d85e62ba5ddccb6674d580481f6febf3da82/airscore/core/frontendUtils.py#L356

**Comment by biuti** [comment]
I noticed that on legapiloti waypoints file are saved with 0 kb. I'll have a look and fix it.

> In the case that we are not using 'waypoint library' then the regions for a comp are available before task creation.

It seems like comp_id is stored in any case, if in session. I'll have a go and see. At the moment I created a region list with link to map and files.

**Comment by biuti** [comment]
waypoint file saving fixed in https://github.com/FAI-CIVL/FAI-Airscore/commit/d00c8a4a3e1c700abfc17d9a57e3b74a5437d77c

Added regions page and region map with download link to public frontend (https://github.com/FAI-CIVL/FAI-Airscore/commit/43dab8fe7208b93f0115e0c1afd646b62b9c13df)

Added link con regions used in competition to competition page (https://github.com/FAI-CIVL/FAI-Airscore/commit/c76b228487d1ab0e0df7b516e0f420853a588e51)
