### ISSUE TITLE
unable to score a task becasuse of telegram_id??

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#135]
unable to score task 111 in airscore_fai database.
Task is stopped.
http://localhost:5000/users/task_score_admin/111.

seems to be sending a row from participants table to FlightResult (Which should take participant obj not a dictionary of participant table row??)

airscore_prod | [2020-11-07 06:31:38,259] ERROR in app: Exception on /users/_score_task/111 [POST]
airscore_prod | Traceback (most recent call last):
airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
airscore_prod |     response = self.full_dispatch_request()
airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
airscore_prod |     rv = self.handle_user_exception(e)
airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
airscore_prod |     reraise(exc_type, exc_value, tb)
airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
airscore_prod |     raise value
airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
airscore_prod |     rv = self.dispatch_request()
airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
airscore_prod |     return self.view_functions[rule.endpoint](**req.view_args)
airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
airscore_prod |     return func(*args, **kwargs)
airscore_prod |   File "/app/airscore/user/views.py", line 1087, in _score_task
airscore_prod |     ref_id, _ = task.create_results(data['status'])
airscore_prod |   File "/app/airscore/core/task.py", line 627, in create_results
airscore_prod |     self.check_all_tracks(lib, airspace, print=print)
airscore_prod |   File "/app/airscore/core/task.py", line 730, in check_all_tracks
airscore_prod |     self.get_pilots()
airscore_prod |   File "/app/airscore/core/task.py", line 807, in get_pilots
airscore_prod |     self.pilots = [FlightResult(**row) for row in P.get_dicts(self.comp_id)]
airscore_prod |   File "/app/airscore/core/task.py", line 807, in <listcomp>
airscore_prod |     self.pilots = [FlightResult(**row) for row in P.get_dicts(self.comp_id)]
airscore_prod |   File "/app/airscore/core/pilot/flightresult.py", line 96, in __init__
airscore_prod |     super().__init__(**kwargs)
airscore_prod |   File "/app/airscore/core/pilot/participant.py", line 39, in __init__
airscore_prod |     super().__init__(**kwargs)
airscore_prod | TypeError: __init__() got an unexpected keyword argument 'telegram_id'

**Comment by philderbeast** [comment]
I can reproduce this error. I imported the [Dalby Big Air 2017](https://github.com/FlareTiming/2017-dalby-bigair-score) and then went to score the first task.

```
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sid/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sid/.local/lib/python3.8/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/home/sid/.local/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/app/airscore/user/views.py", line 1087, in _score_task
    ref_id, _ = task.create_results(data['status'])
  File "/app/airscore/core/task.py", line 627, in create_results
    self.check_all_tracks(lib, airspace, print=print)
  File "/app/airscore/core/task.py", line 730, in check_all_tracks
    self.get_pilots()
  File "/app/airscore/core/task.py", line 807, in get_pilots
    self.pilots = [FlightResult(**row) for row in P.get_dicts(self.comp_id)]
  File "/app/airscore/core/task.py", line 807, in <listcomp>
    self.pilots = [FlightResult(**row) for row in P.get_dicts(self.comp_id)]
  File "/app/airscore/core/pilot/flightresult.py", line 96, in __init__
    super().__init__(**kwargs)
  File "/app/airscore/core/pilot/participant.py", line 39, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'telegram_id'
```

**Comment by kuaka** [comment]
@philderbeast was the 1st task of dalby 2017 stopped?

**Comment by philderbeast** [comment]
@kuaka there weren't any stopped tasks in that comp.

**Comment by kuaka** [comment]
Ok thanks. I had seen in git history that some code around the problem line had been changed to fix an issue with stopped tasks. My task was stopped so wondered if it was related, although I couldn't see how. Looks like it was a red herring.

**Comment by biuti** [comment]
I should have fixed it in https://github.com/FAI-CIVL/FAI-Airscore/commit/92784931eec8d7a9f4c83a3f91ed678608833706.
Both score and full rescore are working now.
Please have a try so we may close this.

**Comment by kuaka** [comment]
For me, this fixes the Telegram issue but rescore/full rescore is not working. I have looked into it and there are further issues with a stopped task/full rescore. I will raise this/these as separate issue(s).

@philderbeast if this is working for you, you can close.
