### ISSUE TITLE
Align the scorer admin menu item

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#136]
Please vertically align the scorer admin menu item with the other items in that menu.

![Screen Shot 2020-11-08 at 6 34 45 AM](https://user-images.githubusercontent.com/633283/98463876-a5755400-218c-11eb-9e74-2ebf7c214998.png)

**Comment by biuti** [comment]
In template_refactor branch I already changed this. I'm testing it and I think we can safely merge into development. I'd like you to have a look before if you have time.
