### ISSUE TITLE
Remove the [x] to close the update user details dialog.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#137]
Please remove the [x] to close the update user details dialog. There's [Cancel] and [Save] buttons and they are sufficient.

![Screen Shot 2020-11-08 at 8 08 29 AM](https://user-images.githubusercontent.com/633283/98465836-c2645400-2199-11eb-83f9-fcaafdd2c60f.png)

**Comment by kuaka** [comment]
fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/b139c33820e28603c0ea51f86110c07fc9295404
