### ISSUE TITLE
stopped task validity - missing attributes

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#143]
when trying to score a stopped task (GAP):
  File "/app/airscore/user/views.py", line 1087, in _score_task
    ref_id, _ = task.create_results(data['status'])
  File "/app/airscore/core/task.py", line 636, in create_results
    lib.calculate_results(self)
  File "/app/airscore/core/formulas/gap2016.py", line 152, in calculate_results
    day_quality(task)
  File "/app/airscore/core/formulas/libs/gap.py", line 200, in day_quality
    task.stop_validity = stopped_validity(task)
  File "/app/airscore/core/formulas/libs/gap.py", line 173, in stopped_validity
    avgdist = task.tot_dist_flown / task.pilots_launched / 1000  # avg distance in Km
AttributeError: 'Task' object has no attribute 'tot_dist_flown'

This code is the same for PWCA so probably similar error there.

**Comment by kuaka** [comment]
fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/ad712319d5a01b19dc7a86dded38bdaa850f3d90
however perhaps it is more desirable to change the property instead (tot_distance_flown - > tot_dist_flown) which would match the result file terminology etc.

**Comment by biuti** [comment]
Good point.
We use also those attributes in Results, so I think the best solution would be to have short attributes to be used in code and readable aliases to be used in outputs.
If you think that is acceptable I will modify accordingly.

**Comment by kuaka** [comment]
OK yes please. tot_dist_flown is perfectly readable to me, however as you prefer.
I guess pull the latest development to pick up the change then make the changes (to avoid merge conflicts)

**Comment by biuti** [comment]
Looking at code now.

https://github.com/FAI-CIVL/FAI-Airscore/blob/ad712319d5a01b19dc7a86dded38bdaa850f3d90/airscore/core/task.py#L382-L387
It takes the name from FlightResult attribute.
Is still desirable to change it?

**Comment by kuaka** [comment]
up to you. 
You could add a second property: 
def tot_dist_flown(self): return tot_distance_flown()  
but this seems inelegant.

To me either name is perfectly legible.

**Comment by biuti** [comment]
https://github.com/FAI-CIVL/FAI-Airscore/commit/6dc182374f70fa23913f602f22c677823055b1cf
