### ISSUE TITLE
task.fastest is none when no one in goal.. is that a good thing?

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#144]
task.fastest is none when no pilots in goal:
https://github.com/FAI-CIVL/FAI-Airscore/blob/ad712319d5a01b19dc7a86dded38bdaa850f3d90/airscore/core/task.py#L471-L475

this makes sense, however several times in formulas we are assuming that it is 0 when no one in goal.

https://github.com/FAI-CIVL/FAI-Airscore/blob/ad712319d5a01b19dc7a86dded38bdaa850f3d90/airscore/core/formulas/libs/gap.py#L348-L351

We need to change either the property or where it is used.
There are also other properties that are none if not relevant. e.g. fastest_in_goal, min_goal_time etc

which is preferred?

stopped task scoring is broken as is.

**Comment by biuti** [comment]
I would just change code as it is in gap2020
`if not res.ESS_time:
        return 0`
before the routine.

If I remember correctly, there was a reason to have it None, probably not to be interpreted as a valid time and written as 0 min somewhere.
If you agree with the solution, I'll check all the code changing to `task.fastest or 0` where needed.

**Comment by kuaka** [comment]
ok

**Comment by biuti** [comment]
https://github.com/FAI-CIVL/FAI-Airscore/commit/230800399e9716985f071bc25f71d3e0449a4583
