### ISSUE TITLE
full rescore not running under redis worker

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#145]
full re-score is not running under a redis worker in production setup. 
It is running under flask (GUNICORN WORKER). This causes timeouts and rebooting of Gunicorn workers leading to poor performance. 
This process needs to be moved to a background task (redis controlled worker).

**Comment by biuti** [comment]
Yes, and live tracking process as well.

**Comment by kuaka** [comment]
> Yes, and live tracking process as well.

This is a separate issue and will need to be raised as such. Also,as agreed, post v1

**Comment by kuaka** [comment]
fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/a0cc5d15443426a766d3913604df024a999e613c
