### ISSUE TITLE
Should two views over comps show a different set of comps?

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#146]
I'm logged in as admin and viewing `/` the competitions drop down doesn't show years other than 2020 and doesn't list any comps.

![Screen Shot 2020-11-09 at 5 37 49 AM](https://user-images.githubusercontent.com/633283/98531238-116bc100-224e-11eb-99f2-958f54fa80e0.png)

The selected comp is the only comp listed at `/users/comp_admin`. The only thing I've done with this comp is import it.

![Screen Shot 2020-11-09 at 5 38 32 AM](https://user-images.githubusercontent.com/633283/98531244-13358480-224e-11eb-9399-421925b11587.png)

Should these two views over comps show a different set of comps? Should the year 2017 be available in the drop down of years? Should 2020 available if the only comp I have is from 2017?

**Comment by biuti** [comment]
Strange. I get correctly years list based on available comps:
![image](https://user-images.githubusercontent.com/35658597/98533555-6bd34480-2283-11eb-8ebe-6089cf4d7b83.png)

> Should 2020 available if the only comp I have is from 2017?

I don't think so, I'll have a look how is logic but I'm pretty sure it is a set of Comps date_from

**Comment by biuti** [comment]
So the season selector works like this:
https://github.com/FAI-CIVL/FAI-Airscore/blob/456cd1ee67bcfcb19a9bf888cf863874cb07e727/airscore/public/views.py#L258

Default value is now().year, removed once initialised.
You should see 2020 during page load, than updated with correct seasons according to comps.
