### ISSUE TITLE
Score keeper label {scorekeeperform.scorekeeper.label}}.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#148]
When I go to add a score keeper, the drop down label is odd and has unbalanced curly braces:

![Screen Shot 2020-11-09 at 6 14 39 AM](https://user-images.githubusercontent.com/633283/98534867-1bdc8980-2253-11eb-9928-7cf9344440d4.png)

**Comment by kuaka** [comment]
fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/b54c9bdb06d9dfc6cd9b33ebf423e248f7a797e9
