### ISSUE TITLE
Showing null in the region column of tasks.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#150]
Please show something other than `null` in the region column of tasks.

![Screen Shot 2020-11-09 at 6 22 35 AM](https://user-images.githubusercontent.com/633283/98535454-22b7cc00-2254-11eb-8f48-2b5d357afb4b.png)

**Comment by biuti** [comment]
This is how it is rendered in dev_candidate branch:
![image](https://user-images.githubusercontent.com/35658597/98538015-70e7c200-228a-11eb-9f76-2a509fe3ec3d.png)
