### ISSUE TITLE
database creation file: basic certifications / rankings / classifications to be added

### ISSUE THREAD

**Issue by biuti** [FAI-CIVL/FAI-Airscore#151]
To avoid errors and make it simpler, I think we should have basic classifications for HG and PG.
I added some rows to have a basic Overall classification for both HG and PG, but also added certifications.
In the future we should add a admin page to create new Classifications.

```
INSERT INTO tblClassification (cat_id, cat_name, comp_class, female, team) VALUES
(1,	'Overall',	'PG',	1,	0),
(2,	'Overall',	'HG',	1,	0);

INSERT INTO tblRanking (rank_id, rank_name, comp_class) VALUES
(1,	'Overall',	'PG'),
(2,	'Serial Class',	'PG'),
(3,	'Sport Class',	'PG'),
(4,	'Fun Class',	'PG'),
(5,	'Overall',	'HG');

INSERT INTO tblCertification (cert_id, cert_name, comp_class, cert_order) VALUES
(1,	'A',	'PG',	1),
(2,	'B',	'PG',	2),
(3,	'C',	'PG',	3),
(4,	'D',	'PG',	4),
(5,	'CCC',	'PG',	5),
(6,	'Class 1',	'HG',	1),
(7,	'Class 5',	'HG',	2);

INSERT INTO tblClasCertRank (cat_id, cert_id, rank_id) VALUES
(1,	5,	1),
(2,	7,	5);
```

There is a column more in certification table, `cert_order`. At the moment it is not used but I guess it will be useful to order certifications when changed / deleted / added not in exact order.

If you agree, I'd add them to basic database creation.

**Comment by kuaka** [comment]
I am not familiar with these tables and how they work but of course it makes sense to have them populated with normal values. Certifications are universal for example.

Certifications - I guess DHV (PG) is pretty much obsolete?

tblClasCertRank - if I understand this correctly, shouldn't there be many more rows in this table ? e.g. for overall PG there should be every certification (A,B,C,D,CCC) and not just CCC?

**Comment by biuti** [comment]
I tested using different certification gliders and they all are listed in Overall. I think at the moment logic is to list all certifications with id <= of id in table. It has to be changed next release to a more flexible logic.

**Comment by kuaka** [comment]
can this be closed?

**Comment by biuti** [comment]
I think so, all my imports or comp creation worked ok.
I still need to add an admin page to create new ones, but there should be no bug at the moment.
As it is thanked for different comps in different parts of the world, I am skeptical about a database of classifications visible to everybody, I rather think it should be possible to select a standard one or create one suitable for the comp in a table like 
comp_id, ranking name, max_cert_allowed.
I'm not sure we need to do this on first release tho, as I cannot really say how long would it take.

**Comment by kuaka** [comment]
I am trying to encourage closing of issues otherwise we'll have a lot of issues and we won't know what is fixed and what is not.
This issue is purely about adding some data into tables on DB creation.

the rest of the front end stuff would be a separate issue that has not been opened as far as I know.
When/if that issue is opened or the work is done you can refer to our telegram conversation on the 31st of October for an idea about how to make custom classifications.

**Comment by biuti** [comment]
So it can be closed.
