### ISSUE TITLE
External Pilot upload from Excel - more info needed

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#152]
The upload Excel option (for registering pilots) does not state that this is the excel generated from airtribune. 
Furthermore, it would be useful to have a standard downloadable template (and indicate which fields are optional/not optional) for scorekeepers that wish to bulk upload via excel that are not using airtribune.

**Comment by biuti** [comment]
Added details, template file download (https://github.com/FAI-CIVL/FAI-Airscore/commit/6d5a8922d70918d63debb8fe105e3255ae832a98)

**Comment by biuti** [comment]
added track_source management in pilot_admin (https://github.com/FAI-CIVL/FAI-Airscore/commit/63939aee31457537b54e78b2db353696c2ffff93)
