### ISSUE TITLE
manually add/modify pilot - country field

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#153]
The manually add or modify pilot has a free text field for country. I think that this should be limited (with a drop down for example, or just straight field validation) to the list of ISO country codes that are already in the DB.

**Comment by biuti** [comment]
Yes, I was waiting as FAI uses different country codes, so before adding them to our db and create the logic I would like to understand if we will use directly their table, or if we will add their updated table when creating our database.
If you think is is necessary I'll add it now anyway.

**Comment by kuaka** [comment]
I don't know what FAI use but it would be strange if it's not an international standard. In any case the civl id is the important identifier when communicating results to FAI. 

All that is needed for airscore is consistency. If it's free text you will end up with a nation's ranking where IT, ITA, and Italy are 3 separate countries.

**Comment by biuti** [comment]
I asked Laura to let us know what's their preferred solution, and to give me the FAI country codes.
I remember from the worlds they wanted to be sure we were using the correct ones. There are few differences from the international codes I don't remember now.
It is more for published documents than for results communication.
As soon as we have an answer I'll transform it to a dropbox.

**Comment by biuti** [comment]
Ok so they use IOC codes. I'll add them to database and use them for the dropdown where needed.

**Comment by kuaka** [comment]
Probably best to put country name as the label in the dropdown and the code
as the value. So the user will see 'Italy' but ITA will be saved. This will
avoid mistakes where the code isn't well known and just assumed.

**Comment by biuti** [comment]
Yes I did so (https://github.com/FAI-CIVL/FAI-Airscore/commit/242b1ade0d8384d76f6c90b37d27f2b5f2f93918)

**Comment by kuaka** [comment]
Don't forget to modify airscore.sql.

**Comment by kuaka** [comment]
with this commit the branch will not run without a modified DB to connect to.

**Comment by biuti** [comment]
tblCountryCodes needs to be updated

**Comment by kuaka** [comment]
yes. Apologies, I see that the sql was updated in a previous commit to the one above. Is there any point having all those codes in the DB? is02,iso3,ioc?  for the future just in case? downside is that the table has to be updated for existing DBs.

**Comment by kuaka** [comment]
airscore_fai DB has been updated.

**Comment by biuti** [comment]
Future use even if I don't see why, but mainly because code of some functions needs to be changed if we drop some columns. I think we could safely do that in a future release.

**Comment by kuaka** [comment]
Ok. I think that for such a low importance issue changes to the database
should be avoided after a release. It would mean that all existing DBs
would need a migration if they were to update airscore.

**Comment by biuti** [comment]
So would you prefer to delete unused columns and simplify function now?

**Comment by kuaka** [comment]
all I am saying is that at release there should be no forseen changes to the DB. Especially because there is not (yet) an automatic DB migration mechanism. If these columns were to be deleted in the future 'just to be tidy' then that is asking a lot of admins of existing installs to go and change their DBs. 
This also means that issue #111 should be adressed sooner rather than later.
Regarding these particular columns, if they will possibly be useful keep them, if not get rid of them, but the decision should be made pre-release IMHO
