### ISSUE TITLE
Airscore/data/images -is it needed?

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#159]
The folder contains a lot of images from Geoff's version and the old php version. Are any files there used? We have airscore/static/img for images.

**Comment by biuti** [comment]
I don't think so.
I never used it.

**Comment by kuaka** [comment]
removed with https://github.com/FAI-CIVL/FAI-Airscore/commit/161f6d12ec4e742db75cbf9dc2cb1a076576cb4e
