### ISSUE TITLE
change "Event Mangement" - > "Management"

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#161]
![image](https://user-images.githubusercontent.com/19358239/99621820-ab710c00-2a8d-11eb-9f69-18a0c374c734.png)
in english "event management" has a specific meaning. When applied to PG/HG comps this is basically the function of airtribune more than airscore.
Suggest that "event management" be changed back to simply "management"

see [event management](https://en.wikipedia.org/wiki/Event_management)

**Comment by biuti** [comment]
Done with https://github.com/FAI-CIVL/FAI-Airscore/commit/5343bb3345fdfc6e6ce3f60eb9b3c1de6bc263e3
