### ISSUE TITLE
has DB process changed?

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#164]
development branch seems a lot (2x) slower than previously when querying the DB.

Has something changed or just a coincidence?

**Comment by biuti** [comment]
In row.save_or_update() https://github.com/FAI-CIVL/FAI-Airscore/commit/98d1029feca0751488affdae8c573834095a4c72 and in row.from_obj() https://github.com/FAI-CIVL/FAI-Airscore/commit/b5e7d5044eb4146ab6bd51d95a5816093fef4b8a we needed to add a check on db that row with given key exists, so we make one access more, but I don't think this should make a huge difference.
