### ISSUE TITLE
unable to see existing results

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#165]
airscore_prod |   File "/app/airscore/user/views.py", line 975, in _get_task_result_files
airscore_prod |     return frontendUtils.get_task_result_files(int(taskid), compid, int(offset))
airscore_prod |   File "/app/airscore/core/frontendUtils.py", line 1403, in get_task_result_files
airscore_prod |     comp_published = time.ctime(comp_file['file_stats']['timestamp'] + offset)
airscore_prod | TypeError: 'NoneType' object is not subscriptable

existing result files unable to be displayed.. I guess the file format has changed? 
I can't re-score because of issue #162

post release we must not have breaking changes with old score files. We should be able to display all result files, even ones that were generated previous to latest version.

**Comment by biuti** [comment]
`['file_stats']['timestamp']` should always be there from first version. Are you sure it could find all result files that are in db?
I will put a check so it will not break if a file is missing.

**Comment by biuti** [comment]
I pushed https://github.com/FAI-CIVL/FAI-Airscore/commit/9592bafca91bcfa07cda64d53629d716eaf47489 to display in results list is file is missing.

**Comment by biuti** [comment]
Did you check if the problem was related to this (file missing) or another issue?

**Comment by kuaka** [comment]
this now fails in a nice way. Not yet scored is displayed next to each task. closing.
