### ISSUE TITLE
Forbes Airspace not compatible

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#166]
Clicking "Area map | download" in forbes (airscore_fai db) /region_map/36?compid=53 results in 500 error.
I believe that the [airspace file](http://www.forbesflatlands.com/images/2020_forbes_airspace.txt) is not what was expected:

airscore_prod |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
airscore_prod |     return self.view_functions[rule.endpoint](**req.view_args)
airscore_prod |   File "/app/airscore/public/views.py", line 553, in region_map
airscore_prod |     waypoints, reg_map, airspace_list, _ = frontendUtils.get_region_waypoints(regid, region=region)
airscore_prod |   File "/app/airscore/core/frontendUtils.py", line 1422, in get_region_waypoints
airscore_prod |     openair_file, airspace_layer, airspace_list, _ = create_airspace_layer(reg_id, region=region, openair_file=openair_file)
airscore_prod |   File "/app/airscore/core/mapUtils.py", line 387, in create_airspace_layer
airscore_prod |     data = read_airspace_map_file(openair_file)
airscore_prod |   File "/app/airscore/core/airspaceUtils.py", line 314, in read_airspace_map_file
airscore_prod |     create_airspace_map_check_files(openair_filename)
airscore_prod |   File "/app/airscore/core/airspaceUtils.py", line 269, in create_airspace_map_check_files
airscore_prod |     bbox = get_airspace_bbox(reader_2)
airscore_prod |   File "/app/airscore/core/mapUtils.py", line 78, in get_airspace_bbox
airscore_prod |     for element in record['elements']:
airscore_prod | TypeError: 'NoneType' object is not subscriptable

**Comment by biuti** [comment]
Is it possible that the region has an openair file associated that is not in data folder?

**Comment by kuaka** [comment]
This is a compatibility issue of the fil. Available in the link above.
Will error when you upload it I believe. Or at least if you try to draw the map.

**Comment by biuti** [comment]
Ok probably I found the problem. As we are using aero files library I'll try to find a workaround.
When adding a region with openair file, I'll check file, if not valid I'll try to patch, otherwise I'll import only wpts.
The problem seems to be double spaces in fixes lines.

**Comment by kuaka** [comment]
as joerg said there is no standard for openair files. So there will always probably be the possibility that some files are not compatible. However it would be good to have a collection of files to test with.

**Comment by biuti** [comment]
I just pushed an updated import function: https://github.com/FAI-CIVL/FAI-Airscore/commit/14128907d8ae0001674b692625c26cc37b8cb20f
- tries to import openair file as is
- if fails, reformats file and tries again
- some feedback is added on frontend about number of spaces imported, and if it was necessary to modify original file.

I tested with Forbes and some other openair files I have, but I'll flag to test
