### ISSUE TITLE
disable telegram button

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#167]
In track_admin there is a "update telegram" (should be "send telegram update") should be able to be disabled (and disabled by default) in defines.yml.
I believe that this is really only a LP feature. If it is intended to be a multi organisation feature (e.g. FAI) then each comp will need it's own use/not use telegram and telegram credentials.

**Comment by biuti** [comment]
Added telegram feature switch, default off (https://github.com/FAI-CIVL/FAI-Airscore/commit/efed7778963dc416652484d88ed3176a5451c8cf)
As we said we should change database the least possible after release, so we have to think a proper way to add features.
I'll open an issue.
