### ISSUE TITLE
when importing fsdb ignore stop_time unless task_state="STOPPED"

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#171]
importing [forbes 2018 fsdb](https://github.com/FlareTiming/2018-forbes-flatlands-score/blob/master/forbes2018.clean-fsdb.xml) into a clean database then deleting the 'fake' tracks and uploading the real [igc files ](https://github.com/FlareTiming/2018-forbes-flatlands-score/tree/master/task%202) results in no pilot reaching goal. However in the [official scores](https://github.com/FlareTiming/2018-forbes-flatlands-score/blob/master/report-official/task2.html) several pilots are in goal.

Looking at the airscore track maps I can see pilots making goal but they are not considered in goal:
![image](https://user-images.githubusercontent.com/19358239/99652350-96f83800-2abc-11eb-8858-004eedf22af8.png)
![image](https://user-images.githubusercontent.com/19358239/99652459-ba22e780-2abc-11eb-878a-64d7ceffec1d.png)
![image](https://user-images.githubusercontent.com/19358239/99652677-00784680-2abd-11eb-8693-b6581626587b.png)
![image](https://user-images.githubusercontent.com/19358239/99652785-243b8c80-2abd-11eb-8577-c226d4e79d27.png)

wondering if there is a problem with the imported task deadlines or something, although the time on the track points near goal are well within the deadline in task settings.

**Comment by kuaka** [comment]
This also causes scoring to fail as difficulty calculation errors with index out of range. So there are tracks that have flown further than the max landout distance. Which is inconsistent. These could be those that should have made goal.

**Comment by biuti** [comment]
I can see that a stopped time was imported:
![image](https://user-images.githubusercontent.com/35658597/99688749-71503c00-2a86-11eb-83e8-02b03740f76c.png)

Probably with all tasks. The xml file has a `stop_time` in every task, should be `""`.
Try deleting stopped time in settings and let me know.
I will also change the timings page so that if multi start and / or stopped time are set, panels are open.

**Comment by kuaka** [comment]
ok thanks. good spotting. I have raised a question here:
https://github.com/FlareTiming/2018-forbes-flatlands-score/issues/3
It may be a flaretiming issue or an airscore issue, depending on what the fsdb "standard" is.

**Comment by kuaka** [comment]
removing the stopped time and doing a full re-score fixes the problem. I will not close issue until we hear the outcome of the issue on FlareTiming

**Comment by philderbeast** [comment]
I ignore the stopped time unless it is a stopped task. I'm not sure that's the right thing to do.

**Comment by kuaka** [comment]
I looked at the [2019 Italian open file](https://github.com/FlareTiming/2019-italy-score/blob/master/italy2019.clean-fsdb.xml)
this also is of the same format (stop_time present for every task). Therefore airScore should use the same logic as Flare Timing and only consider the stop_time if task_state="STOPPED"

**Comment by kuaka** [comment]
fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/8fad6a6592b91c56c82b2000b6d24171120fb37f
tested with  [forbes 2018 fsdb ](https://github.com/FlareTiming/2018-forbes-flatlands-score/blob/master/forbes2018.clean-fsdb.xml)
