### ISSUE TITLE
result file generation on FSDB importing

### ISSUE THREAD

**Issue by biuti** [FAI-CIVL/FAI-Airscore#172]
I think it could be useful to create this file, with 'Imported Results' in status or comments, to have simpler procedures when we need to have them in ladders, or just to keep the original results when we the recalculate in Airscore.

**Comment by biuti** [comment]
Results are created during import process (8fef514)

**Comment by kuaka** [comment]
this is working for me in that results are generated and visible in users/task_score_admin/ however issue #173 still applies.
