### ISSUE TITLE
imported fsdb & then scored - no results 

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#173]
If a comp is imported from fsdb, then tracks uploaded and scored no results display.
Seems that the link to results is ext_comp_result/ and no results are displayed. page says "calculating results.." and hangs.

**Comment by biuti** [comment]
My test flow was:
- Imported Forbes 2018 fsdb file
- activated tasks and comp results
- results displayed in ext_competition page
- converted comp to airscore
- imported tracks and scored task 1
- activated task results and comp results
- results are displayed in competition page

Everything worked as expected apart:
- have to change task result page for ext comp as task_result has links to map that obviously fails

**Comment by kuaka** [comment]
>     * Imported Forbes 2018 fsdb file
> 
>     * activated tasks and comp results
> 
>     * results displayed in ext_competition page

what do you mean by "**activated tasks and comp results**" ? I only see the **convert** option.

**Comment by biuti** [comment]
All task and comp results are imported as non active. To be displayed they need to be activated.
I guess we could add a "Import and Activate" checkbox in import fsdb modal.

![image](https://user-images.githubusercontent.com/35658597/100527831-8c355580-31d6-11eb-882b-127b4c7b52a5.png)

**Comment by kuaka** [comment]
Do you mean published?

**Comment by biuti** [comment]
yes published. They are active or not in database.

**Comment by kuaka** [comment]
this issue can be closed as it is fixed. 
However, if the below proceedure were to be done from a fresh install of airscore (i.e. no data folder) I believe it would cause an error. See #123 

> My test flow was:
> 
>     * Imported Forbes 2018 fsdb file
> 
>     * activated tasks and comp results
> 
>     * results displayed in ext_competition page
> 
>     * converted comp to airscore
> 
>     * imported tracks and scored task 1
> 
>     * activated task results and comp results
> 
>     * results are displayed in competition page
> 
> 
> Everything worked as expected apart:
> 
>     * have to change task result page for ext comp as task_result has links to map that obviously fails
