### ISSUE TITLE
Thank you for registering

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#181]
On registration, I'm getting the toast that I can log in but I'm already logged in:

>Thank you for registering. You can now log in.

Please change the toast.

![Screen Shot 2020-11-22 at 6 45 18 AM](https://user-images.githubusercontent.com/633283/99902838-b21aa180-2c8e-11eb-82f2-8299b7f35d67.png)

**Comment by kuaka** [comment]
I have tested this. For me it seems that the new user is automatically logged in only in the case that it is the admin account (first account) and not subsequent scorekeeper accounts. From your screenshot it looks like the same for you.
commit https://github.com/FAI-CIVL/FAI-Airscore/commit/3864b2a5a1acf8793b6f2a0647522bffe5cf99e4 should fix this.

**Comment by philderbeast** [comment]
Yes this was on first account registration.
