### ISSUE TITLE
Repeated overview entry for the same comp

### ISSUE THREAD

**Issue by biuti** [FAI-CIVL/FAI-Airscore#184]
There was a bug that added a row in database each time the overview result file for a comp was updated, so multiple rows referred to the same file.
Bug has been corrected with https://github.com/FAI-CIVL/FAI-Airscore/commit/445531a1680b586cd560e4d558d0a364f93fb1fe, but now you could get an error if more than one row is found with the same filename.
So you need to delete all rows that have the same filename ending with `_Overview`.

**Comment by kuaka** [comment]
Probably not really a bug. This was the expected behaviour (one row per file update) but I agree it's not necessary for this file. However the row must be updated with created timestamp as the competition page uses the latest file. I think that your commit does update the timestamp but please test.
