### ISSUE TITLE
time for some linting?

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#185]
if you run the flake8 linter
sudo docker-compose -f docker-compose-tests.yml run --rm tests lint
(or on any dev container) almost every file has fixes and reformats. Would need to be reviewed.

**Comment by philderbeast** [comment]
I've installed the [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension for the code editor and it shows a lot of warnings too when I'm looking at airScore.

![Screen Shot 2020-11-25 at 9 18 14 AM](https://user-images.githubusercontent.com/633283/100239258-32473e00-2eff-11eb-9ea3-58d558b21abd.png)

**Comment by kuaka** [comment]
looks like you don't have the dependencies installed and the environment setup for airScore on your system. 
If you want to run code/ import libraries on your system you would have to have them installed on your system or in a virtual env associated with the project.
As airscore runs in a docker container that has all of this installed it is not an issue for running the app.

**Comment by kuaka** [comment]
I have adjusted some settings with https://github.com/FAI-CIVL/FAI-Airscore/commit/232863cb3c9ee6f4ed467536e661908e16b18d21 and https://github.com/FAI-CIVL/FAI-Airscore/commit/21088bb14ad8133775cdb93a3f239e5f2e6ce908. 

I have linted with https://github.com/FAI-CIVL/FAI-Airscore/commit/06d4db99704b8e3c5a71ee66a14eafc74fee2e47 and https://github.com/FAI-CIVL/FAI-Airscore/commit/56b35c7552d5f6f78e218535a2ee7209fc7e11a7. 

This should be done periodically (or ideally before commits) or could be set up with a GitHub action.
