### ISSUE TITLE
Is optimised path from each fix to ESS used for leading area?

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#187]
Is the leading area calculated using an optimised path from each fix to ESS? It looks like it might be using distance to the next cylinder added to the optimal route for the task from that cylinder to ESS, the faster simplified distance calculation.

https://github.com/FAI-CIVL/FAI-Airscore/blob/a279e3e29077590ec5d4f9501b601b6e62912644/airscore/core/formulas/libs/leadcoeff.py#L27

https://github.com/FAI-CIVL/FAI-Airscore/blob/a279e3e29077590ec5d4f9501b601b6e62912644/airscore/core/flightcheck/flightcheck.py#L236-L245

**Comment by biuti** [comment]
In one case distance_flown is the simplified function, in the other is the pilot attribute, which during speedsecrion is calculated using the precise opt distance from fix to ess.
Ciao
