### ISSUE TITLE
Five comps, four external and one internal.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#188]
I imported Forbes 2018 twice, left the first one as external and converted the second one to internal. With the internal one, I used [fsdb_igc](https://github.com/kuaka/fsdb_igc) to create task tracklog zip files and then proceeded to upload these for each task. Looking at the competitions page I now see five comps, four external and one internal.

![Screen Shot 2020-11-27 at 8 29 56 AM](https://user-images.githubusercontent.com/633283/100454600-3a33e900-308b-11eb-9473-d75340b3496e.png)

**Comment by kuaka** [comment]
I strongly suspect that this is a result of multiple attempts at importing the comp and running into the missing dir issue. 
In which case the comp would have been imported but results not generated. The page would not have refreshed as the process did not complete but had it been refreshed it most likely would have shown the comp.

**Comment by philderbeast** [comment]
OK, leave it with me for a bit and I'll try to reproduce it.

**Comment by philderbeast** [comment]
I'll try this tomorrow.

**Comment by kuaka** [comment]
closing. if it occurs again it can be reopened.
