### ISSUE TITLE
competition page not updated when task scored & published

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#190]
related to #178 and a direct result of https://github.com/FAI-CIVL/FAI-Airscore/commit/573378f85b8925d67e9edb0eb4dc0a655f470283 in particular:https://github.com/FAI-CIVL/FAI-Airscore/commit/573378f85b8925d67e9edb0eb4dc0a655f470283#r44602227
the competition page is not updated with the latest task scoring information.
please roll back https://github.com/FAI-CIVL/FAI-Airscore/commit/573378f85b8925d67e9edb0eb4dc0a655f470283

**Comment by kuaka** [comment]
if I score and publish a task (7) this is the result:
![image](https://user-images.githubusercontent.com/19358239/100483123-28bb1180-315d-11eb-98a8-1a44ce5a47eb.png)

this is the expected behaviour:
![image](https://user-images.githubusercontent.com/19358239/100483044-1c36b900-315d-11eb-97ba-89f161f9dcd6.png)

**Comment by biuti** [comment]
ops I forgot, committed now https://github.com/FAI-CIVL/FAI-Airscore/commit/99a8c2e9e6d7fa65ac3c43c125ea85e24692dfa1
