### ISSUE TITLE
unclear UI in comp result

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#191]
![image](https://user-images.githubusercontent.com/19358239/100489154-78a6d200-3177-11eb-8448-84b19c21619f.png)
the front end describes activating a file called "overview" I can't see where this "file" is and how to "activate" it.
The process is not clear and I am not sure why we need this text.

**Comment by biuti** [comment]
Yes, I forgot to update. Committed now https://github.com/FAI-CIVL/FAI-Airscore/commit/ea5ee637efef6dd278106468992b78404f763600

The idea is that the user can just activate the file that is generated by Airscore, and the comp results are automatically kept uptodate.
Or, activate own generated comp result and manage then when to update, keep daily event standings saved, and so on.

**Comment by kuaka** [comment]
Ok I understand. Good idea just very unclear in front end.
