### ISSUE TITLE
bulk file import name patterns not communicated

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#193]
![image](https://user-images.githubusercontent.com/19358239/100526326-9e41e300-322c-11eb-96d4-ecca80340181.png)
the message does not list the formats available in defines.py.
Need to include all or provide a link to a list or something.

**Comment by biuti** [comment]
Changed to this in https://github.com/FAI-CIVL/FAI-Airscore/commit/032504f0ab75de0b3e23c6fa89417950e1549fd4
![image](https://user-images.githubusercontent.com/35658597/100528367-5e530f80-31dc-11eb-8bbd-9d9b8ca0f13d.png)
