### ISSUE TITLE
confusing message in scoring

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#194]
![image](https://user-images.githubusercontent.com/19358239/101947381-44421400-3c55-11eb-8a1b-1b4b806f524e.png)
message talks about not having results so cannot score.. results are the product of scoring so is not clear. 
Would be clearer if it used 'tracks' instead of 'results'

**Comment by biuti** [comment]
fixed, thanks (https://github.com/FAI-CIVL/FAI-Airscore/commit/e82f539893c9b255767539b47585357d3b7a01430)

**Comment by biuti** [comment]
I think all typos or bad wording in messages could go here.

**Comment by kuaka** [comment]
> I think all typos or bad wording in messages could go here.

Where?

**Comment by kuaka** [comment]
this is something that @philderbeast has mentioned before but the best practice rule in software development is one bug/question etc -> one issue.
Otherwise it is too hard and confusing to manage.
