### ISSUE TITLE
unable to create a region without airspace file

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#195]
Commit 45941af7edd9cadcb9e3efd98842326732035252
removing this line https://github.com/FAI-CIVL/FAI-Airscore/commit/45941af7edd9cadcb9e3efd98842326732035252#r45126645
breaks creating a region without airspace.

**Please** properly test any changes you make before committing (or at least pushing to GitHub) it is **extremely** frustrating to have airScore constantly (re)broken

`airscore_prod |   File "/app/airscore/user/views.py", line 1335, in region_admin
airscore_prod |     openair_file=air_filename, turnpoints=wpts)
airscore_prod | UnboundLocalError: local variable 'air_filename' referenced before assignment
`

**Comment by biuti** [comment]
fixed (https://github.com/FAI-CIVL/FAI-Airscore/commit/6fb76903a04b4397d9fa52f0a7cda1213b2e3325)
