### ISSUE TITLE
bad flash message on task setting.

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#196]
![image](https://user-images.githubusercontent.com/19358239/102188287-fa3d8480-3f19-11eb-93f1-9539ff2eeb72.png)
commit 675e3ac639e7e0ebfe074a4e0fc675251f3fe297 causes this bad formatting.
I believe a similar change has also been made to comp form error messages.

**..again please test your changes before committing!**

**Comment by biuti** [comment]
fixed (https://github.com/FAI-CIVL/FAI-Airscore/commit/1f25b6bd6a666c6013a275dc05a8ae5ae7d62d1b)
