### ISSUE TITLE
Create a comp. public website link broken

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#197]
if you create a comp before scoring the link on the public website is broken.

This used to work with pages for comp not ready etc.

`airscore_prod |     result_file = get_comp_json(compid, overview=True)
airscore_prod |   File "/app/airscore/core/compUtils.py", line 95, in get_comp_json
airscore_prod |     data = open_json_file(get_comp_json_filename(comp_id, latest, overview))
airscore_prod |   File "/app/airscore/core/compUtils.py", line 85, in get_comp_json_filename
airscore_prod |     filename = next(row for row in results if 'Overview' in row.filename).filename
`

**Comment by biuti** [comment]
fixed (https://github.com/FAI-CIVL/FAI-Airscore/commit/dac20f4754240483bae0e03d702357d201c0c3e4)
