### ISSUE TITLE
link from track management goes to map with bad "back to results" link

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#198]
![image](https://user-images.githubusercontent.com/19358239/102257988-49af9f00-3f72-11eb-9edc-6d6b77782e0e.png)
the above link goes to map page with "back to results" link which is broken when there are no results yet.

**Comment by biuti** [comment]
fixed (https://github.com/FAI-CIVL/FAI-Airscore/commit/7eecbc14019c6fb0b3f4d8d21b9110d415ab1893)
