### ISSUE TITLE
creating comp all fields mandatory but no indication/feedback

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#202]
Creating a comp if the user does not provide all info (such as location) then there is an error but there is no feedback to the user.
There either should be checking that all info has been provided prior to post request or something like a flash message as an error that some info was missing.

**Comment by biuti** [comment]
I added Flask form to create_comp procedure, now supports flashed messages, with errors feedback (https://github.com/FAI-CIVL/FAI-Airscore/commit/50fd3481d0e31d3a8e062201ecd7d837b1d0b0e6)
