### ISSUE TITLE
Cancelled import is not cancelled.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#212]
If I picked the wrong `*.fsdb` to import and cancel the import then the next time I go to import it seems the same file is still being imported. I had picked the 2018 comp for import but cancelled because it is the 2019 comp I meant to import. The [Cancel] button hides the dialog and the [Import] button brings it back, determined to import the comp I'd cancelled the import of.

![Screen Shot 2020-12-19 at 10 41 11 AM](https://user-images.githubusercontent.com/633283/102693198-dfebfb00-41e6-11eb-8809-271990455f80.png)

**Comment by biuti** [comment]
The cancel button is intended just to close the modal panel.
Once selected a file in browse, process starts and cannot be stopped.
I can see if we can hide buttons once process starts.

**Comment by biuti** [comment]
I've updated comp_admin FSDB importing to support flashed messages about process and results auto publish function
(https://github.com/FAI-CIVL/FAI-Airscore/commit/50fd3481d0e31d3a8e062201ecd7d837b1d0b0e6)
