### ISSUE TITLE
warning recieved during testing

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#214]
`tests/test_fsdb.py::test_fsdb_import
  /app/airscore/core/pilot/participant.py:150: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
    if live and live.isdigit():

-- Docs: https://docs.pytest.org/en/stable/warnings.html
`

**Comment by biuti** [comment]
corrected with https://github.com/FAI-CIVL/FAI-Airscore/commit/f4c3860da717b028548487ca76a91b97388ff8c0
I also updated other warning for future deprecation (https://github.com/FAI-CIVL/FAI-Airscore/commit/7457a32215f4ecb1d85e4b74a6e49133243b2e63).
I saw there are some that should be updated in igc_lib, maybe they already did it?

**Comment by kuaka** [comment]
> I saw there are some that should be updated in igc_lib, maybe they already did it?
I don't believe so but you can check [here](https://github.com/xiadz/igc_lib) last commit was 11 months ago.
You can create a PR if you would like.
