### ISSUE TITLE
sql file - create table before view

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#217]
from @biuti:

I also saw that in Airscore.sql we create tables to delete and replace them with views. Is there a reason for that or could we simplify the procedure?

**Comment by kuaka** [comment]
the sql script is automatically exported from phpmyadmin. So your question would be for mySQL or possibly phpmyadmin teams.
However I would suggest that it creates a table as a placeholder so it can build the schema then creates the view. If it were to create the view first it would probably need all the input tables and views created first so order of creation would be important and that is probably a lot of logic that it needs to work out what to create 1st. Just my idea.

**Comment by biuti** [comment]
I asked because I saw that it deletes them (obviously) before creating views, I suppose it is not needed as far as views are created after all tables, but this is by default I guess.
I will try to find something to read about it.

**Comment by kuaka** [comment]
yes it drops them but only before creating the view. It does not drop all at once. So when a view is created everything else that it may use exists (either in table form or view form).
I'm curious as to why you are interested in this.
It is a script run once (for a second or so) at airScore installation. It is also a script that is planned to be deprecated when views are removed and alembic is used for DB migration. Given all the issues with airScore at the moment what is to gain by changing this?
