### ISSUE TITLE
Pilots marked NYP when they are DFNT.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#219]
For the 2019 Dalmatian XC Paragliding Open imported from `*.fsdb` airScore is not reading the **DFNT** status of two pilots and marking them as **NYP** instead. Here's the pilot status table from flare-timing.

Id | Name | Task 1 | Task 2
-- | -- | -- | --
35 | Giselle Giampietri | DFNoTrack | DFNoTrack
10 | Igor Eržen |   |  
11 | Jerko Odžak |   |  
32 | Laura Grakalich | DFNoTrack | DFNoTrack
15 | Mitja Jug |   |  
18 | Petros Miskos |   |  
19 | Rafal Cypcar |   |  
22 | Sandi Krč |   |  
24 | Slava Jelić |   |  
26 | Stjepan Zjacic |   |

**Comment by philderbeast** [comment]
How to [parse](https://flare-timing.readthedocs.io/en/latest/extract-input.html#pilot-groups) pilot groups from the XML of an `*.fsdb` file.

**Comment by kuaka** [comment]
Airscore does not currently support did fly no track.

Related to #103 and #232

**Comment by biuti** [comment]
I update the function(https://github.com/FAI-CIVL/FAI-Airscore/issues/232#issuecomment-751813251)
Now they are correctly reported as `mindist`.

![image](https://user-images.githubusercontent.com/35658597/103351656-2cb3b980-4aa4-11eb-9551-1e4905103601.png)
