### ISSUE TITLE
Parse ABS status.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#224]
Importing from `*.fsdb` please parse ABS status for pilots.

**Comment by philderbeast** [comment]
Those pilots ABS for task 3, 2018 XC Dalmatian Paragliding Open.

Id | Name
-- | --
13 | Balazs Szatmari
50 | Josip Osmann
53 | Konstantin Rakić
82 | Richard Edlinger
86 | Sandi Krč
88 | Sandor Roza
94 | Stjepan Zjacic
102 | Tomislav Gomerčić
113 | Zsolt Sandor

**Comment by philderbeast** [comment]
After importing tracks for task 1, Konstantin is NYP but should be ABS.

ID | Name | Result |  
-- | -- | -- | --
53 | Konstantin Rakić | NYP | Delete Track

**Comment by philderbeast** [comment]
In the [Results] tab for an imported but external event, airScore is showing DNF and ABS status but forgetting this when I convert the comp to airScore and [Bulk Import Tracks]. Please preserve the ABS status after importing tracks, especially if there is no track for an ABS pilot.

**Comment by kuaka** [comment]
see https://github.com/FAI-CIVL/FAI-Airscore/issues/225#issuecomment-751436171
