### ISSUE TITLE
Sort users alphabetically in track admin table.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#226]
Please have the default view of `/users/track_admin/1` sort users alphabetically.

![Screen Shot 2020-12-25 at 7 07 03 AM](https://user-images.githubusercontent.com/633283/103134547-e9aaae00-467f-11eb-83c3-4fb7a966a545.png)

**Comment by kuaka** [comment]
looks like is was in reverse alphabetical order. fixed with https://github.com/FAI-CIVL/FAI-Airscore/commit/b1ddc8eace93012dcffcdd361a16071a8e89795a
