### ISSUE TITLE
Typo in default turnpoint tolerance for GAP2016.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#228]
The default turnpoint tolerance for GAP2016 should be 0.5% or 0.005.

https://github.com/FAI-CIVL/FAI-Airscore/blob/a69c4694e256ba3cc87a87e2fe4e5e3b0559e8b0/airscore/core/formulas/gap2016.py#L69-L70

https://github.com/FAI-CIVL/FAI-Airscore/blob/a69c4694e256ba3cc87a87e2fe4e5e3b0559e8b0/airscore/core/formulas/gap2016.py#L121-L122

**Comment by kuaka** [comment]
fixed.
