### ISSUE TITLE
Empty the field, Minimum turnpoint tolerance.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#229]
If in the competition formula if I make an edit so that there is no value in "Minimum turnpoint tolerance (m)", an empty string, then please take that to mean a value of zero. I get this error if I try:

    Minimum turnpoint tolerance (m) (None): Not a valid integer value

**Comment by kuaka** [comment]
you can simply set to zero.
This is standard behavior for an integer field in the form library that we use.
We can [override it and accept a blank](https://stackoverflow.com/questions/46761931/integerfield-not-validating-on-empty-string) then force the blank to be a zero in the code (in which case you will see a zero upon page refresh as that is what will be saved to the database).
For consistency we would need to do this to every integer field in airScore.

I don't think it is too much to ask the user to put zero in when they mean zero. There is a message after all that tells them what is wrong.

**Comment by philderbeast** [comment]
For this setting, a zero absolute minimum is the same as not doing the minimum check, the same as doing nothing, a "None" action. For this setting having no value does make sense but I'm not going to push for this. I raised the issue because to me it felt more natural to delete the value 5 than it did to set it to 0.
