### ISSUE TITLE
Don't change the spelling of pilot names on import.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#230]
Please don't change the spelling of pilot names on import. For the 2018 XC Dalmatian Paragliding Open don't make the following change:

```diff
-- Nuno Filipe da Fonseca Bastos Gomes
++ Nuno Filipe Da Fonseca Bastos Gomes

-- Ricardo Nicolau Soares Terra de Oliveira Figueiredo
++ Ricardo Nicolau Soares Terra De Oliveira Figueiredo
```

A snippet of the `*.fsdb`:

```xml
<FsParticipant id="74" name="Nuno Filipe da Fonseca Bastos Gomes" />
<FsParticipant id="80" name="Ricardo Nicolau Soares Terra de Oliveira Figueiredo" />
```

**Comment by kuaka** [comment]
above commit should fix this. I have tested with importing 2018 XC Dalmatian Paragliding Open.
please test and close if ok.

**Comment by philderbeast** [comment]
From the table "Registered Pilot Details" before the fix:

![Screen Shot 2020-12-26 at 8 42 15 PM](https://user-images.githubusercontent.com/633283/103162160-ed8f1b00-47ba-11eb-8d75-72d7e8f3e5e9.png)

After the fix with the spelling from the `*.fsdb` preserved:

![Screen Shot 2020-12-26 at 8 42 34 PM](https://user-images.githubusercontent.com/633283/103162161-ed8f1b00-47ba-11eb-91bc-c7bad731be61.png)
