### ISSUE TITLE
formula.get_fsdb_info hard to read

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#231]
`get_fsdb_info(formula, form):`

the get_fsdb_info function is missing a doc string and due to using "formula" and  "form" as internal variables it is very hard to read.
"form" is used elsewhere in the app for frontend forms but in this case I think it is the formula section of the fsdb file. would be better to rename it to something more self evident like fsdb_formula.

**Comment by biuti** [comment]
https://github.com/FAI-CIVL/FAI-Airscore/issues/233#issuecomment-751450493
