### ISSUE TITLE
Suan Selenati is scored 640 points too little.

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#250]
For meduno 2020, task 2, the external score (the FS score) of pilot 118 Suan Selenati is 714 but the airScore one is only 74.

![Screen Shot 2021-04-15 at 2 43 15 PM](https://user-images.githubusercontent.com/633283/114921769-ef77fb00-9df8-11eb-8f50-8b553d70e6c9.png)
![Screen Shot 2021-04-15 at 2 43 05 PM](https://user-images.githubusercontent.com/633283/114921770-ef77fb00-9df8-11eb-8034-a171957516ce.png)

**Comment by philderbeast** [comment]
Pilot 103, Joerg Bajewski is similar, given 74 points by airScore but 392 by FS.

**Comment by biuti** [comment]
I think you did not change Start from out/enter to In/Exit.
FS does not have that info.

**Comment by philderbeast** [comment]
I see in the 2020 v2 GAP doc that there is "No more prescribed turnpoint direction (including start)" but is this something airScore needs I enter?

**Comment by philderbeast** [comment]
> I think you did not change Start from out/enter to In/Exit.

That corrects this problem.
