### ISSUE TITLE
No module named 'wtforms.fields.html5'

### ISSUE THREAD

**Issue by goatchurchprime** [FAI-CIVL/FAI-Airscore#293]
The fix, according to here, is to downgrade the **WTF**orms library.

https://stackoverflow.com/questions/70068407/modulenotfounderror-no-module-named-wtforms-fields-html5

The line is here:
   https://github.com/FAI-CIVL/FAI-Airscore/blob/development/requirements/prod.txt#L18

We changed it into an ==

**Comment by kuaka** [comment]
can this be closed with 33b449d8027c08cc80a24f7cfa38f5f476ab6022 ?

**Comment by biuti** [comment]
Yes I think so, instead of sticking to version 3 I changed the code. I also tested with an old version of Airscore with old library version and it works as well, so we should be fine.
