### ISSUE TITLE
.env variable "app" not defined

### ISSUE THREAD

**Issue by JEK58** [FAI-CIVL/FAI-Airscore#302]
In the `.env.example` `PYTHONPATH` is defined as `PYTHONPATH=${app}:src` but I could not find any place where `app` is actually defined.

**Comment by biuti** [comment]
In Dockerfile it is made explicit a default path that is working for a standard installation.
In my working build that env line is unchanged

**Comment by JEK58** [comment]
Hm, I'm not sure if I understood you correctly.
In the Dockerfile `ENV PYTHONPATH="${PYTHONPATH}:/app/airscore/core:/app"` it is set to the value from .env wich as I mentioned above is constructed from the non existents `app` variable.

It also gives me an error `WARN[0000] The "app" variable is not set. Defaulting to a blank string. ` when starting the container.

**Comment by biuti** [comment]
I committed a new env example file that avoids warning during launch. That should not change anything, as there are alternatives separated by colon in Dockerfile. It is a test variable I could remove as well.
Please have a try

**Comment by JEK58** [comment]
Looks good to me
