### ISSUE TITLE
Running the local production docker compose fails

### ISSUE THREAD

**Issue by JEK58** [FAI-CIVL/FAI-Airscore#303]
Running the local production docker compose `docker-compose -f docker-compose-prod-local.yml up` fails with the following error: `* error decoding 'command': invalid command line string`

Changing this line

`command: gunicorn airscore.app:create_app() -b :5000 -w ${GUNICORN_WORKERS} -k gevent`

to 

`command: gunicorn 'airscore.app:create_app()' -b ':5000' -w ${GUNICORN_WORKERS} -k gevent`

will fix the error.

But after visiting `localhost:5000` and creating a 1st admin it fails on registering with the following error 

```
airscore_prod          | [2023-07-04 09:39:19,174] ERROR in app: Exception on /setup_admin/ [POST]
airscore_prod          | Traceback (most recent call last):
airscore_prod          |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
airscore_prod          |     response = self.full_dispatch_request()
airscore_prod          |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
airscore_prod          |     rv = self.handle_user_exception(e)
airscore_prod          |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
airscore_prod          |     rv = self.dispatch_request()
airscore_prod          |   File "/home/sid/.local/lib/python3.8/site-packages/flask/app.py", line 1503, in dispatch_request
airscore_prod          |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
airscore_prod          |   File "/app/airscore/public/views.py", line 193, in setup_admin
airscore_prod          |     if form.validate_on_submit():
airscore_prod          |   File "/home/sid/.local/lib/python3.8/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
airscore_prod          |     return self.is_submitted() and self.validate(extra_validators=extra_validators)
airscore_prod          | TypeError: validate() got an unexpected keyword argument 'extra_validators'
```

BTW: The same error occurs when running the production version with `docker compose up`

Intel Mac 
MacOS13.4.1

Docker versions: 
Engine: 24.0.2
Compose: v2.19.1

**Comment by biuti** [comment]
That's has been already reported, I cannot replicate myself.
It seems a solution could be changing: 
/airscore/public/form.py line 23
`initial_validation = super(LoginForm, self).validate()`
to 
`initial_validation = super(LoginForm, self).validate(extra_validators=None)`
and same in /airscore/user/forms.py lines 64 and 78

I'm testing it before committing, also to understand why I don't have this issue in my build
I will shortly commit anyway as an interim fix

**Comment by JEK58** [comment]
That did not work. I have no idea of python, but reading the error I tried the following and that seems to work:

Changing every 

`def validate(self):`

to

`def validate(self, extra_validators=None):`

/airscore/public/form.py line 20
/airscore/user/forms.py lines 62 

There may probably be more places where this would have to be changed.

**Comment by biuti** [comment]
I committed a fix, please have a try

**Comment by JEK58** [comment]
Thanks, works for me now.
