### ISSUE TITLE
Add 1st admin page shows up even if admin account exists

### ISSUE THREAD

**Issue by JEK58** [FAI-CIVL/FAI-Airscore#304]
Steps to reproduce:

Start new production deployment with fresh DB
Visit page
Register 1st admin
Logout
Visit page
=> Register 1st admin prompt still show up (and allows to create another admin!)

If I stay logged in as admin a click the "public website" link I will be redirected to the `setup_admin/`page but it will be populated with the 404 page.

Manually navigating to `/`will then show the comp list as expected.
But only as long as I stay logged in. Otherwise => 1st admin register prompt as described above.

**Comment by biuti** [comment]
I made some commits yesterday and today, try to pull and test again please.
I just set a server from scratch and it worked

**Comment by JEK58** [comment]
I don't understand why the commits helped with that behaviour but I cannot reproduce it anymore.

**Comment by biuti** [comment]
that's encouraging :)
Please close this if this is solved on your side

**Comment by JEK58** [comment]
Will close this, but could you maybe point me to the commit that solved this behaviour, or was it actually a coincidence?
