### ISSUE TITLE
Adding a user as admin does not work

### ISSUE THREAD

**Issue by JEK58** [FAI-CIVL/FAI-Airscore#305]
Tested both in local-production and production.

Pressing "save" will initiate request that fails with a "504" after some while.

<img width="712" alt="Screenshot 2023-07-07 at 19 06 50" src="https://github.com/FAI-CIVL/FAI-Airscore/assets/35194489/8162b47c-d0f2-4231-abfb-b2618509986e">

**Comment by biuti** [comment]
I just did it, user was added and mail received.
What's the error in log?

**Comment by JEK58** [comment]
It was a misconfiguration of the email server. 
But there was basically no error log that would tell you about what would be wrong.
Had to add some `print()` to actually find out what went wrong. (If you wait long enough the client would actually hint that it has something to do with sending emails.)

**Comment by biuti** [comment]
Yes there's a lot of feedback to add, to help users and admins to solve issues. This is probably an important one, code should check and prevent to add users if smtp settings are not proper.

I'd like ideally to use print statement in tests, and remove / comment out them in release, I also created a log method to keep track of certain processes. But meanwhile probably you're right.

Can we close this then?

**Comment by JEK58** [comment]
Yep, will close this. Maybe have a look at the PR regarding the unbuffered logs: https://github.com/FAI-CIVL/FAI-Airscore/pull/306
