### ISSUE TITLE
A checklist of scoring features that are included or not?

### ISSUE THREAD

**Issue by philderbeast** [FAI-CIVL/FAI-Airscore#42]
Could we add a [checklist](https://github.com/BlockScope/flare-timing#whats-included) of scoring features that are included or not?

**Comment by philderbeast** [comment]
@kuaka and @biuti I'll leave this issue open until features in airscore have been checked off.

**Comment by kuaka** [comment]
I have filled this in to the best of my knowledge. I have also added a couple of points. see commit https://github.com/FAI-CIVL/FAI-Airscore/commit/4ecdb7d20f6be7206698eaaf06dd864c99a6153f

@biuti could you please check these and make any required changes. In particular the scored time window. I believe that we do this but I am not 100% sure. https://github.com/FAI-CIVL/FAI-Airscore/issues/113#issuecomment-716202079

Once you have checked and made any changes this can be closed.

**Comment by kuaka** [comment]
I forgot teams ranking for comps. added. https://github.com/FAI-CIVL/FAI-Airscore/commit/77e5d834037ad04173276ec98dfeeb02b65cbfda

**Comment by biuti** [comment]
What @kuaka filled seems uptodate. 
line 46: There is GAP2019 instead of PWC2019
line 96: if that is the new distance weight formula in GAP2020, then it is calculated.

**Comment by kuaka** [comment]
> line 96: if that is the new distance weight formula in GAP2020, then it is calculated.

I am not exactly sure what it is, but given that it is under parameter tweaks I assume that it is something that the scorer can adjust and not just part of a standard formula. @philderbeast  will be able to elaborate.

>line 46: There is GAP2019 instead of PWC2019

please make any changes and commit & push.

**Comment by biuti** [comment]
https://github.com/FAI-CIVL/FAI-Airscore/commit/7df436ef298f17063e0d8ac13b576719b2bc493e
