### ISSUE TITLE
airspace map no longer displaying

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#81]
Airspace map shows a map but with no airspace.
route: /users/airspace_map/<filename>

**Comment by biuti** [comment]
https://airscore.legapiloti.it/users/airspace_map/poggio2020%20openair.txt
It seems to work to me (packages branch).

**Comment by kuaka** [comment]
Ok, The issue is that the airspace layer in the map is hidden by default. This should be active by default.

**Comment by kuaka** [comment]
I think that this has been resolved in packages but needs to be merged into Dev.

**Comment by kuaka** [comment]
merged
