### ISSUE TITLE
CSS for small screens (smartphones)

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#82]
Competition overview page does not display well on phones. the maps are the issue. 
This should be an easy fix as this page was taken from Geoffs repo and his displays well on mobiles.

**Comment by kuaka** [comment]
commit https://github.com/FAI-CIVL/FAI-Airscore/commit/e55c9510f3f7641955f4dcd7c4c947e90b2dcf57 fixes issue with maps and task details on competition overview page on small screens. (the task details now flow under the map). 
Will not close yet in case there are other CSS changes needed for small screens.

![image](https://user-images.githubusercontent.com/19358239/94385024-87d1c980-01a0-11eb-9779-f02e132bd4ee.png)

**Comment by kuaka** [comment]
@biuti  is there anything else or can we close?

**Comment by biuti** [comment]
I'm working at the moment on a new admin frontend version to be more easy to read and responsive, and to uniform rendering style among pages.
As soon as I'm finished, I'll apply useful CSS styling to public frontend as well.
You can leave this open and close it and open a new one if you think better.

![image](https://user-images.githubusercontent.com/35658597/95555722-814e1800-0a12-11eb-8fd7-0476057fa5ef.png)

**Comment by kuaka** [comment]
I don't know how this page works. It took me a while to realize that the blue buttons at the top in horizontal are not links to other pages and are for the settings. The buttons "scoring" and "tracks" look like they should go to the scoring and track management pages.. The original "scoring parameters" and something like "checks" or "Track checks" would be a lot clearer. A native English speaker would not use "managing" as a button name but would use "management" (not sure why you decided to change). But it is your choice.

**Comment by biuti** [comment]
The idea is to separate main form from secondary that are saved using different add/save buttons, so it will be easier to understand workflow. I moved save button under tabs selectors, probably text has to be improved as you say to be clearer.
Some layout can be applied to task setting and other pages.

**Comment by kuaka** [comment]
original issue fixed and merged to dev
