### ISSUE TITLE
export results as HTML

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#93]
create export of results as HTML

I think this needs to go in the public area

**Comment by philderbeast** [comment]
So would this be the same format that FS publishes to html today?

I'm tracking that too with https://github.com/BlockScope/flare-timing/issues/61.

**Comment by kuaka** [comment]
Antonio has done the work but it's not merged to dev branch yet. I believe that he has followed the same format as FS. @biuti is this correct?

**Comment by biuti** [comment]
Yes, that is correct.
I just switched total result column in comp overall results to be in front of task results, but if needed we can change it easily.
I started from a FS template, and changed it to be dinamically generated by flask.

**Comment by biuti** [comment]
Attaching some examples, let us know.

--
Antonio Golfari
antoniogolfari@gmail.com
39 347 3701187

**Comment by philderbeast** [comment]
Since we now have 3 projects between us using those FS templates might it not be a good idea to spin them out into their own repo?

**Comment by biuti** [comment]
Feature added (https://github.com/FAI-CIVL/FAI-Airscore/commit/5b4a70fef83994a158ee60cc939986379392803d)
