### ISSUE TITLE
Add live_id xcontest_id to pilot admin add / update pilot

### ISSUE THREAD

**Issue by kuaka** [FAI-CIVL/FAI-Airscore#98]
add these 2 IDs (that are already present in DB and object) to the pilot admin (add and update)

**Comment by kuaka** [comment]
some work has been done on this however:

1. When track source is set to xcontest - xcontest field is present in registered pilot list (datatable) and in edit modal - this is correct behaviour.
2. When track source is set to "-" then no source displayed in pilot list or edit modal - this is correct
3. When track source is set to flymaster_livetrack then both xcontest and live ID are in the edit modal - **this is not correct** and neither of these are in the list (datatable) - **incorrect**

**Comment by biuti** [comment]
I'm not able to replicate. Checking DataTables, edit and save new meals, they seem to work as intended using all 3 options.

**Comment by kuaka** [comment]
still an issue for me.

**Set live track & save:**
![image](https://user-images.githubusercontent.com/19358239/99998821-1f137000-2e24-11eb-9a43-ee366be61f75.png)

**no live id in table:**
![image](https://user-images.githubusercontent.com/19358239/99998854-2f2b4f80-2e24-11eb-883c-03b5c6b09825.png)

**both in edit:**
![image](https://user-images.githubusercontent.com/19358239/99998902-436f4c80-2e24-11eb-9987-83d945b3fc97.png)

**Comment by biuti** [comment]
ok so the issue is that you have 'flymaster_livetrack' instead of 'flymaster'. How is that?

**Comment by kuaka** [comment]
>     3. When track source is set to flymaster_livetrack then both xcontest and live ID are in the edit modal - **this is not correct** and neither of these are in the list (datatable) - **incorrect**

this is the issue.
I am on dev branch

**Comment by kuaka** [comment]
looks like the names are the same as in defines. This highlights the issue of keeping defines out of git. There obvioulsly has been a change to the example file but I haven't picked it up as it is very subtle. I will change the name and re-test

**Comment by kuaka** [comment]
OK if I change defines to have "flymaster" the issue goes away.

in my opionion "flymaster livetrack" is clearer than flymaster. As someone could mistake 'flymaster' to mean the instrument and not the service.
